# Generated by Django 6.0.4 on 2026-04-28 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='The player dealing this round', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealt_rounds', to='scoring.sessionplayer'),
        ),
    ]
