# Generated by Django 6.0.4 on 2026-05-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_created_by_player_email_player_updated_at_and_more'),
        ('scoring', '0002_round_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The player group roster this session was drawn from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='players.playergroup'),
        ),
        migrations.AddField(
            model_name='session',
            name='token',
            field=models.CharField(blank=True, db_index=True, help_text='Short-lived token allowing unauthenticated scoring access', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='token_expires',
            field=models.DateTimeField(blank=True, help_text='When the scoring token expires — session becomes read-only', null=True),
        ),
        migrations.AlterField(
            model_name='round',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealt_rounds', to='scoring.sessionplayer'),
        ),
    ]
