# Generated by Django 6.0.4 on 2026-05-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_session_group_session_token_session_token_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked rounds are complete and display-only unless unlocked for editing'),
        ),
    ]
