# Generated by Django 6.0.4 on 2026-04-11 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('play_mode', models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=20)),
                ('scoring_mode', models.CharField(choices=[('cumulative', 'Cumulative (highest wins)'), ('target', 'Target Score (first to reach wins)'), ('lowest_wins', 'Lowest Score Wins')], default='cumulative', max_length=20)),
                ('winning_score', models.IntegerField(blank=True, help_text='Leave blank for open-ended games with no score limit', null=True)),
                ('num_rounds', models.IntegerField(blank=True, help_text='Leave blank for open-ended games with no round limit', null=True)),
                ('allow_negative', models.BooleanField(default=False, help_text='Whether negative scores are allowed (e.g. penalty points)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
