# Generated by Django 6.0.4 on 2026-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_scoring',
            field=models.CharField(choices=[('team', 'One score per team per round'), ('individual', 'Each player scores, team totals sum')], default='team', help_text='Only applies when Play Mode is Team', max_length=20),
        ),
    ]
