# Generated by Django 6.0.4 on 2026-04-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_team_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='requires_dealer',
            field=models.BooleanField(default=False, help_text='Whether or not the dealer rotates between people'),
        ),
    ]
